In [2]:
import pandas as pd
df= pd.read_excel("data/dead_conso-3-54-65.xlsx")
df

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
0,8600677,2554,2011,72.0,1.0,99,วังหลวง,กิ่ง อ.เฝ้าไร่,นค,NaN,...,2554-07-13 00:00:00,2554-07-12 00:00:00,1900-01-01 16:34:00,หนองหลวง,กิ่ง อ.เฝ้าไร่,อุดรธานี,18.020541,103.187171,V031,คนเดินเท้า
1,8600520,2554,2011,17.0,1.0,99,ภูฝ้าย,ขุนหาญ,ศก,NaN,...,2554-01-22 00:00:00,2554-01-20 00:00:00,1900-01-01 22:00:00,เมืองใต้,เมืองศรีสะเกษ,ศรีสะเกษ,15.117497,104.327475,V294,รถจักรยานยนต์
2,8600600,2554,2011,44.0,1.0,99,คลองเตย,คลองเตย,กท,NaN,...,2554-06-01 00:00:00,2554-05-29 00:00:00,1900-01-01 18:00:00,สุรศักดิ์,ศรีราชา,ชลบุรี,NaN,NaN,V299,รถจักรยานยนต์
3,8600625,2554,2011,43.0,1.0,99,วัดสุวรรณ,บ่อทอง,ชบ,NaN,...,2554-01-19 00:00:00,2554-01-18 00:00:00,1900-01-01 21:40:00,บ่อวิน,ศรีราชา,ชลบุรี,NaN,NaN,V892,ไม่ระบุพาหนะ
4,8600681,2554,2011,35.0,1.0,99,เหล่าต่างคำ,โพนพิสัย,นค,NaN,...,2554-08-16 00:00:00,2554-07-29 00:00:00,1900-01-01 23:16:00,ช่องสามหมอ,แก้งคร้อ,ขอนแก่น,16.122191,102.220463,V892,ไม่ระบุพาหนะ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238394,1072503,2565,2022,20.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,ลำพูน,18.404682,98.724158,Y349,ไม่ระบุพาหนะ
238395,1076343,2565,2022,66.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-20 00:00:00,NaN,NaT,NaN,NaN,ฉะเชิงเทรา,13.692206,101.073257,V892,รถบรรทุกขนาดเล็ก/รถตู้
238396,1078903,2565,2022,70.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,มหาสารคาม,16.122524,103.253255,V892,รถจักรยานยนต์
238397,1082487,2565,2022,65.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-10 00:00:00,NaN,NaT,NaN,NaN,พังงา,8.515615,98.287358,Y349,รถจักรยานยนต์
238398,1078648,2565,2022,71.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-03 00:00:00,NaN,NaT,NaN,NaN,เลย,17.727573,101.716185,V892,ไม่ระบุพาหนะ

In [3]:
df["Vehicle"].unique()

array(['คนเดินเท้า', 'รถจักรยานยนต์', 'ไม่ระบุพาหนะ',
       'รถบรรทุกขนาดเล็ก/รถตู้', 'รถยนต์', 'สามล้อ', 'รถโดยสาร',
       'รถบรรทุกหนัก', 'รถจักรยาน', 'รถเพื่อการเกษตร'], dtype=object)

In [5]:
walker = df[df["Vehicle"].str.contains("คนเดินเท้า")]
walker

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
0,8600677,2554,2011,72.0,1.0,99,วังหลวง,กิ่ง อ.เฝ้าไร่,นค,NaN,...,2554-07-13 00:00:00,2554-07-12 00:00:00,1900-01-01 16:34:00,หนองหลวง,กิ่ง อ.เฝ้าไร่,อุดรธานี,18.020541,103.187171,V031,คนเดินเท้า
34,8597199,2554,2011,61.0,1.0,99,กำแพง,ละงู,สต,NaN,...,2554-03-29 00:00:00,2554-03-29 00:00:00,1900-01-01 20:30:00,กำแพง,ละงู,สตูล,6.882247,99.781335,V091,คนเดินเท้า
61,8600714,2554,2011,57.0,1.0,99,ห้วยข้าวก่ำ,จุน,พย,NaN,...,2554-02-18 00:00:00,2554-02-17 00:00:00,1900-01-01 20:15:00,แม่เจดีย์ใหม่,เวียงป่าเป้า,พะเยา,NaN,NaN,V091,คนเดินเท้า
103,8595982,2554,2011,20.0,1.0,99,ด่านช้าง,ด่านช้าง,สพ,NaN,...,2554-01-24 00:00:00,2554-01-24 00:00:00,1900-01-01 19:16:00,หนองมะค่าโมง,ด่านช้าง,สุพรรณบุรี,14.889479,99.751687,V041,คนเดินเท้า
106,8595811,2554,2011,39.0,1.0,99,นอกเมือง,เมืองสุรินทร์,สร,NaN,...,2554-02-27 00:00:00,2554-02-27 00:00:00,1900-01-01 14:40:00,หนองเต็ง,กระสัง,บุรีรัมย์,14.915215,103.368423,V031,คนเดินเท้า
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238297,1079129,2565,2022,54.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-13 00:00:00,NaN,NaT,NaN,NaN,ร้อยเอ็ด,16.412126,103.761122,V031,คนเดินเท้า
238326,1071458,2565,2022,36.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-25 00:00:00,NaN,NaT,NaN,NaN,เลย,17.447337,101.490413,V041,คนเดินเท้า
238350,1078121,2565,2022,42.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-08 00:00:00,NaN,NaT,NaN,NaN,ขอนแก่น,16.459884,102.635578,V099,คนเดินเท้า
238352,1073258,2565,2022,28.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-02-23 00:00:00,NaN,NaT,NaN,NaN,ตาก,17.016839,99.102019,V099,คนเดินเท้า
238376,1082481,2565,2022,50.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-27 00:00:00,NaN,NaT,NaN,NaN,พังงา,8.459554,98.587775,V099,คนเดินเท้า

In [6]:
motorcycle = df[df["Vehicle"].str.contains("รถจักรยานยนต์")]
motorcycle

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
1,8600520,2554,2011,17.0,1.0,99,ภูฝ้าย,ขุนหาญ,ศก,NaN,...,2554-01-22 00:00:00,2554-01-20 00:00:00,1900-01-01 22:00:00,เมืองใต้,เมืองศรีสะเกษ,ศรีสะเกษ,15.117497,104.327475,V294,รถจักรยานยนต์
2,8600600,2554,2011,44.0,1.0,99,คลองเตย,คลองเตย,กท,NaN,...,2554-06-01 00:00:00,2554-05-29 00:00:00,1900-01-01 18:00:00,สุรศักดิ์,ศรีราชา,ชลบุรี,NaN,NaN,V299,รถจักรยานยนต์
5,8600678,2554,2011,31.0,1.0,99,นากอก,ศรีบุญเรือง,นภ,NaN,...,2554-06-25 00:00:00,2554-06-23 00:00:00,1900-01-01 10:24:00,ลำภู,เมือง,อุดรธานี,16.870271,102.184005,V229,รถจักรยานยนต์
6,8600568,2554,2011,25.0,1.0,99,ท่าไร่,เมือง,นศ,NaN,...,2554-08-10 00:00:00,2554-08-09 00:00:00,1900-01-01 23:20:00,ท่าไร่,เมือง,นครศรีธรรมราช,8.433131,100.046831,V299,รถจักรยานยนต์
10,8600726,2554,2011,59.0,1.0,99,คณฑี,เมืองกำแพงเพชร,กพ,NaN,...,2554-08-25 00:00:00,2554-08-20 00:00:00,1900-01-01 15:00:00,เทพนคร,เมืองกำแพงเพชร,นครสวรรค์,NaN,NaN,V234,รถจักรยานยนต์
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238378,1073522,2565,2022,38.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-13 00:00:00,NaN,NaT,NaN,NaN,เพชรบูรณ์,16.410514,101.089078,Y349,รถจักรยานยนต์
238388,1078901,2565,2022,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-12 00:00:00,NaN,NaT,NaN,NaN,มหาสารคาม,16.188095,103.224892,V892,รถจักรยานยนต์
238391,1077878,2565,2022,45.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-17 00:00:00,NaN,NaT,NaN,NaN,ยโสธร,15.731645,104.321018,V892,รถจักรยานยนต์
238396,1078903,2565,2022,70.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,มหาสารคาม,16.122524,103.253255,V892,รถจักรยานยนต์
238397,1082487,2565,2022,65.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-10 00:00:00,NaN,NaT,NaN,NaN,พังงา,8.515615,98.287358,Y349,รถจักรยานยนต์

In [7]:
no_vehicle_specified = df[df["Vehicle"].str.contains("ไม่ระบุพาหนะ")]
no_vehicle_specified

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
3,8600625,2554,2011,43.0,1.0,99,วัดสุวรรณ,บ่อทอง,ชบ,NaN,...,2554-01-19 00:00:00,2554-01-18 00:00:00,1900-01-01 21:40:00,บ่อวิน,ศรีราชา,ชลบุรี,NaN,NaN,V892,ไม่ระบุพาหนะ
4,8600681,2554,2011,35.0,1.0,99,เหล่าต่างคำ,โพนพิสัย,นค,NaN,...,2554-08-16 00:00:00,2554-07-29 00:00:00,1900-01-01 23:16:00,ช่องสามหมอ,แก้งคร้อ,ขอนแก่น,16.122191,102.220463,V892,ไม่ระบุพาหนะ
7,8600508,2554,2011,24.0,1.0,99,บางลี่,ท่าวุ้ง,ลบ,NaN,...,2554-01-23 00:00:00,2554-01-03 00:00:00,1900-01-01 15:00:00,ท่าวุ้ง,ท่าวุ้ง,ลพบุรี,14.812265,100.505089,V892,ไม่ระบุพาหนะ
8,8600645,2554,2011,29.0,1.0,99,คำเนียม,กันทรารมย์,ศก,NaN,...,2554-10-12 00:00:00,2554-10-10 00:00:00,1900-01-01 00:00:00,หนองแก้ว,กันทรารมย์,อุบลราชธานี,15.159277,104.666316,V892,ไม่ระบุพาหนะ
9,8600684,2554,2011,49.0,1.0,99,แหลมฟ้าผ่า,พระสมุทรเจดีย์,สป,NaN,...,2554-11-23 00:00:00,2554-11-22 00:00:00,1900-01-01 21:01:00,แหลมฟ้าผ่า,พระสมุทรเจดีย์,สมุทรปราการ,NaN,NaN,V892,ไม่ระบุพาหนะ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238389,1072502,2565,2022,21.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,ลำพูน,18.404682,98.724158,Y349,ไม่ระบุพาหนะ
238392,1079414,2565,2022,61.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-06-08 00:00:00,NaN,NaT,NaN,NaN,นครราชสีมา,15.105716,101.442571,V892,ไม่ระบุพาหนะ
238393,1081974,2565,2022,49.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-06 00:00:00,NaN,NaT,NaN,NaN,สมุทรสาคร,13.464010,100.098558,Y349,ไม่ระบุพาหนะ
238394,1072503,2565,2022,20.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,ลำพูน,18.404682,98.724158,Y349,ไม่ระบุพาหนะ
238398,1078648,2565,2022,71.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-03 00:00:00,NaN,NaT,NaN,NaN,เลย,17.727573,101.716185,V892,ไม่ระบุพาหนะ

In [8]:
small_trucks_vans = df[df["Vehicle"].str.contains("รถบรรทุกขนาดเล็ก/รถตู้")]
small_trucks_vans

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
17,8598239,2554,2011,0.0,1.0,99,โนนตาล,ท่าอุเทน,นพ,NaN,...,2554-09-21 00:00:00,2554-09-21 00:00:00,1900-01-01 14:00:00,NaN,ท่าอุเทน,นครพนม,17.549264,104.578946,V536,รถบรรทุกขนาดเล็ก/รถตู้
68,8598444,2554,2011,19.0,1.0,99,เพี้ยราม,เมืองสุรินทร์,สร,NaN,...,2554-10-25 00:00:00,2554-10-25 00:00:00,1900-01-01 19:40:00,ท่าสว่าง,เมืองสุรินทร์,สุรินทร์,14.924082,103.471358,V536,รถบรรทุกขนาดเล็ก/รถตู้
81,8597807,2554,2011,13.0,1.0,99,สะเตง,เมืองยะลา,ยล,NaN,...,2554-07-12 00:00:00,2554-07-12 00:00:00,1900-01-01 13:05:00,คลองฉนวน,เวียงสระ,สุราษฎร์ธานี,8.534807,99.329343,V549,รถบรรทุกขนาดเล็ก/รถตู้
194,8595821,2554,2011,22.0,1.0,99,หนองกรด,บรรพตพิสัย,นว,NaN,...,2554-12-29 00:00:00,2554-12-29 00:00:00,1900-01-01 11:40:00,หนองกรด,บรรพตพิสัย,นครสวรรค์,15.986704,100.109209,V509,รถบรรทุกขนาดเล็ก/รถตู้
254,8596349,2554,2011,17.0,1.0,99,หัวหิน,หัวหิน,ปข,NaN,...,2554-06-12 00:00:00,2554-06-10 00:00:00,1900-01-01 17:10:00,บ้านในดง,ท่ายาง,เพชรบุรี,12.947918,99.945805,V586,รถบรรทุกขนาดเล็ก/รถตู้
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238361,1076334,2565,2022,60.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-20 00:00:00,NaN,NaT,NaN,NaN,ฉะเชิงเทรา,13.692206,101.073257,V892,รถบรรทุกขนาดเล็ก/รถตู้
238373,1072241,2565,2022,21.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-06-02 00:00:00,NaN,NaT,NaN,NaN,จันทบุรี,12.640792,102.172282,V892,รถบรรทุกขนาดเล็ก/รถตู้
238384,1073524,2565,2022,32.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-30 00:00:00,NaN,NaT,NaN,NaN,ตาก,16.780266,99.174727,V546,รถบรรทุกขนาดเล็ก/รถตู้
238390,1073526,2565,2022,31.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-22 00:00:00,NaN,NaT,NaN,NaN,เพชรบูรณ์,16.393162,101.178597,Y349,รถบรรทุกขนาดเล็ก/รถตู้
238395,1076343,2565,2022,66.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-20 00:00:00,NaN,NaT,NaN,NaN,ฉะเชิงเทรา,13.692206,101.073257,V892,รถบรรทุกขนาดเล็ก/รถตู้

In [9]:
car = df[df["Vehicle"].str.contains("รถยนต์")]
car

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
19,8596661,2554,2011,5.0,1.0,99,ปริก,สะเดา,สข,NaN,...,2554-01-10 00:00:00,2554-01-10 00:00:00,1900-01-01 06:20:00,ปริก,สะเดา,สงขลา,NaN,NaN,V499,รถยนต์
29,8597309,2554,2011,23.0,1.0,99,นาข้าวเสีย,นาโยง,ตง,NaN,...,2554-04-16 00:00:00,2554-04-16 00:00:00,1900-01-01 13:20:00,กะลาเส,สิเกา,ตรัง,NaN,NaN,V471,รถยนต์
31,8596876,2554,2011,40.0,1.0,99,พระบาท,เมืองลำปาง,ลป,NaN,...,2554-02-11 00:00:00,2554-02-11 00:00:00,1900-01-01 01:50:00,ชมพู,เมืองลำปาง,ลำปาง,18.269372,99.473305,V435,รถยนต์
32,8598761,2554,2011,25.0,1.0,99,เขาสามสิบ,เขาฉกรรจ์,สก,NaN,...,2554-12-05 00:00:00,2554-12-05 00:00:00,1900-01-01 03:15:00,เขาสามสิบ,เขาฉกรรจ์,สระแก้ว,NaN,NaN,V499,รถยนต์
46,8599014,2554,2011,39.0,1.0,99,ปานัน,มายอ,ปน,NaN,...,2554-08-27 00:00:00,2554-08-27 00:00:00,1900-01-01 13:30:00,กะลุวอ,เมืองนราธิวาส,นราธิวาส,6.359976,101.847821,V499,รถยนต์
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238377,1072242,2565,2022,31.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-01 00:00:00,NaN,NaT,NaN,NaN,มุกดาหาร,16.498794,104.258185,V446,รถยนต์
238379,1079666,2565,2022,50.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-01-30 00:00:00,NaN,NaT,NaN,NaN,เชียงใหม่,19.335763,98.956340,V429,รถยนต์
238381,1072243,2565,2022,20.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-01 00:00:00,NaN,NaT,NaN,NaN,มุกดาหาร,16.498794,104.258185,V446,รถยนต์
238383,1073268,2565,2022,22.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-26 00:00:00,NaN,NaT,NaN,NaN,พัทลุง,7.717627,99.985155,V479,รถยนต์
238387,1076341,2565,2022,74.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-20 00:00:00,NaN,NaT,NaN,NaN,ฉะเชิงเทรา,13.692206,101.073257,V449,รถยนต์

In [10]:
tricycle = df[df["Vehicle"].str.contains("สามล้อ")]
tricycle

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
52,8600452,2554,2011,44.0,1.0,99,ครึ่ง,เชียงของ,ชร,NaN,...,2554-11-10 00:00:00,2554-11-09 00:00:00,1900-01-01 23:30:00,ครึ่ง,เชียงของ,เชียงราย,20.033145,100.375869,V324,สามล้อ
710,8602360,2554,2011,8.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-08-28 00:00:00,NaN,NaT,NaN,NaN,ระยอง,NaN,NaN,V334,สามล้อ
1314,8599673,2554,2011,65.0,1.0,99,โพนางดำออก,สรรพยา,ชน,NaN,...,2554-02-14 00:00:00,2554-02-10 00:00:00,1900-01-01 15:00:00,สรรพยา,สรรพยา,ชัยนาท,15.115318,100.266679,V389,สามล้อ
2793,8614049,2554,2011,67.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-07-09 00:00:00,NaN,NaT,NaN,NaN,สุรินทร์,NaN,NaN,V335,สามล้อ
3205,8601365,2554,2011,49.0,2.0,99,NaN,NaN,NaN,NaN,...,2554-08-09 00:00:00,NaN,NaT,NaN,NaN,เพชรบูรณ์,NaN,NaN,V386,สามล้อ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235263,1078878,2565,2022,48.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-06-20 00:00:00,NaN,NaT,NaN,NaN,บึงกาฬ,NaN,NaN,V399,สามล้อ
236239,1074474,2565,2022,21.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-08 00:00:00,NaN,NaT,NaN,NaN,สตูล,NaN,NaN,V389,สามล้อ
237181,1081802,2565,2022,61.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-07-06 00:00:00,NaN,NaT,NaN,NaN,สุพรรณบุรี,NaN,NaN,V399,สามล้อ
237857,1078781,2565,2022,56.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,บึงกาฬ,NaN,NaN,V399,สามล้อ
238080,1079055,2565,2022,82.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-01-23 00:00:00,NaN,NaT,NaN,NaN,ร้อยเอ็ด,15.759981,103.570276,V385,สามล้อ

In [11]:
bus = df[df["Vehicle"].str.contains("รถโดยสาร")]
bus

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
85,8597390,2554,2011,63.0,1.0,99,ชะอวด,ชะอวด,นศ,NaN,...,2554-05-02 00:00:00,2554-05-02 00:00:00,1900-01-01 13:16:00,นาหมอบุญ,จุฬาภรณ์,นครศรีธรรมราช,8.021903,99.845592,V746,รถโดยสาร
1480,8611807,2554,2011,71.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-10-29 00:00:00,NaN,NaT,NaN,NaN,ตาก,NaN,NaN,V789,รถโดยสาร
2192,8602272,2554,2011,15.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-10-20 00:00:00,NaN,NaT,NaN,NaN,นครศรีธรรมราช,NaN,NaN,V786,รถโดยสาร
2443,8602332,2554,2011,36.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-02-21 00:00:00,NaN,NaT,NaN,NaN,น่าน,NaN,NaN,V799,รถโดยสาร
2832,8612815,2554,2011,47.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-01-23 00:00:00,NaN,NaT,NaN,NaN,พะเยา,NaN,NaN,V789,รถโดยสาร
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222681,11412318,2564,2021,16.0,2.0,99,NaN,NaN,NaN,NaN,...,2564-05-03 00:00:00,NaN,NaT,NaN,NaN,หนองคาย,NaN,NaN,V789,รถโดยสาร
223890,1083870,2565,2022,58.0,1.0,Thai,NaN,เมืองนครปฐม,นครปฐม,NaN,...,2565-09-12 00:00:00,NaN,NaT,ธรรมศาลา,เมืองนครปฐม,นครปฐม,13.812985,100.115618,V892,รถโดยสาร
224970,1072909,2565,2022,26.0,2.0,Thai,NaN,เชียงคำ,พะเยา,NaN,...,2565-02-15 00:00:00,NaN,NaT,บ้านหวด,งาว,ลำปาง,NaN,NaN,X599,รถโดยสาร
230194,1074741,2565,2022,15.0,1.0,Thai,NaN,พนมสารคาม,ฉะเชิงเทรา,NaN,...,2565-07-07 00:00:00,NaN,NaT,เกาะขนุน,พนมสารคาม,ฉะเชิงเทรา,13.685060,101.392186,V892,รถโดยสาร
238286,1079126,2565,2022,59.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-22 00:00:00,NaN,NaT,NaN,NaN,กรุงเทพมหานคร,13.669120,100.416731,V892,รถโดยสาร

In [12]:
heavy_truck = df[df["Vehicle"].str.contains("รถบรรทุกหนัก")]
heavy_truck

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
361,8596386,2554,2011,51.0,1.0,99,โคกคราม,บางปลาม้า,สพ,NaN,...,2554-01-03 00:00:00,2554-01-01 00:00:00,1900-01-01 10:00:00,NaN,บางปลาม้า,สุพรรณบุรี,14.402222,100.152384,V696,รถบรรทุกหนัก
441,8601925,2554,2011,33.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-02-20 00:00:00,NaN,NaT,NaN,NaN,เพชรบุรี,NaN,NaN,V699,รถบรรทุกหนัก
706,8602532,2554,2011,58.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-02-04 00:00:00,NaN,NaT,NaN,NaN,ราชบุรี,NaN,NaN,V699,รถบรรทุกหนัก
859,8602748,2554,2011,39.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-09-29 00:00:00,NaN,NaT,NaN,NaN,นครราชสีมา,NaN,NaN,V646,รถบรรทุกหนัก
2357,8602591,2554,2011,43.0,1.0,99,NaN,NaN,NaN,NaN,...,2554-07-15 00:00:00,NaN,NaT,NaN,NaN,นครราชสีมา,NaN,NaN,V696,รถบรรทุกหนัก
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238176,1083695,2565,2022,60.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-09-02 00:00:00,NaN,NaT,NaN,NaN,เชียงใหม่,18.094586,98.374475,V892,รถบรรทุกหนัก
238255,1081675,2565,2022,47.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-16 00:00:00,NaN,NaT,NaN,NaN,ชัยนาท,15.280458,100.196058,Y349,รถบรรทุกหนัก
238264,1074000,2565,2022,34.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-26 00:00:00,NaN,NaT,NaN,NaN,นครศรีธรรมราช,8.318840,99.920959,V892,รถบรรทุกหนัก
238314,1075296,2565,2022,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-31 00:00:00,NaN,NaT,NaN,NaN,นครปฐม,13.771801,100.207482,V892,รถบรรทุกหนัก
238347,1079912,2565,2022,59.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-08 00:00:00,NaN,NaT,NaN,NaN,ลำปาง,18.552395,99.629342,Y349,รถบรรทุกหนัก

In [13]:
bicycle = df[df["Vehicle"].str.contains("รถจักรยาน")]
bicycle

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
1,8600520,2554,2011,17.0,1.0,99,ภูฝ้าย,ขุนหาญ,ศก,NaN,...,2554-01-22 00:00:00,2554-01-20 00:00:00,1900-01-01 22:00:00,เมืองใต้,เมืองศรีสะเกษ,ศรีสะเกษ,15.117497,104.327475,V294,รถจักรยานยนต์
2,8600600,2554,2011,44.0,1.0,99,คลองเตย,คลองเตย,กท,NaN,...,2554-06-01 00:00:00,2554-05-29 00:00:00,1900-01-01 18:00:00,สุรศักดิ์,ศรีราชา,ชลบุรี,NaN,NaN,V299,รถจักรยานยนต์
5,8600678,2554,2011,31.0,1.0,99,นากอก,ศรีบุญเรือง,นภ,NaN,...,2554-06-25 00:00:00,2554-06-23 00:00:00,1900-01-01 10:24:00,ลำภู,เมือง,อุดรธานี,16.870271,102.184005,V229,รถจักรยานยนต์
6,8600568,2554,2011,25.0,1.0,99,ท่าไร่,เมือง,นศ,NaN,...,2554-08-10 00:00:00,2554-08-09 00:00:00,1900-01-01 23:20:00,ท่าไร่,เมือง,นครศรีธรรมราช,8.433131,100.046831,V299,รถจักรยานยนต์
10,8600726,2554,2011,59.0,1.0,99,คณฑี,เมืองกำแพงเพชร,กพ,NaN,...,2554-08-25 00:00:00,2554-08-20 00:00:00,1900-01-01 15:00:00,เทพนคร,เมืองกำแพงเพชร,นครสวรรค์,NaN,NaN,V234,รถจักรยานยนต์
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238378,1073522,2565,2022,38.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-08-13 00:00:00,NaN,NaT,NaN,NaN,เพชรบูรณ์,16.410514,101.089078,Y349,รถจักรยานยนต์
238388,1078901,2565,2022,55.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-12 00:00:00,NaN,NaT,NaN,NaN,มหาสารคาม,16.188095,103.224892,V892,รถจักรยานยนต์
238391,1077878,2565,2022,45.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-17 00:00:00,NaN,NaT,NaN,NaN,ยโสธร,15.731645,104.321018,V892,รถจักรยานยนต์
238396,1078903,2565,2022,70.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-05 00:00:00,NaN,NaT,NaN,NaN,มหาสารคาม,16.122524,103.253255,V892,รถจักรยานยนต์
238397,1082487,2565,2022,65.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-10 00:00:00,NaN,NaT,NaN,NaN,พังงา,8.515615,98.287358,Y349,รถจักรยานยนต์

In [14]:
agricultural_vehicle = df[df["Vehicle"].str.contains("รถเพื่อการเกษตร")]
agricultural_vehicle

,id,DEAD_YEAR(Budha),DEAD_YEAR,Age,Sex,NationalityId,Tumbol,District,Province,RiskHelmet,...,DeadDate,DateRec,Time Rec,AccSubDist,AccDist,AccProv,AccLat,AccLong,ICD-10,Vehicle
131740,9798875,2560,2017,44.0,1.0,99,NaN,NaN,NaN,NaN,...,2560-05-29 00:00:00,2560-05-29 00:00:00,1900-01-01 11:00:00,หนองหญ้าขาว,สีคิ้ว,นครราชสีมา,14.959889,101.571450,V849,รถเพื่อการเกษตร
131741,9800964,2560,2017,43.0,1.0,99,NaN,NaN,NaN,NaN,...,2560-12-07 00:00:00,2560-12-07 00:00:00,1900-01-01 11:52:00,พระธาตุบังพวน,เมืองหนองคาย,หนองคาย,17.752756,102.691666,V892,รถเพื่อการเกษตร
133550,9807226,2560,2017,25.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2560-05-12 00:00:00,2560-05-12 00:00:00,1900-01-01 19:00:00,บัวใหญ่,บัวใหญ่,นครราชสีมา,15.555649,102.422158,NaN,รถเพื่อการเกษตร
133551,9808080,2560,2017,39.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2560-12-31 00:00:00,2560-12-31 00:00:00,1900-01-01 21:00:00,โนน,โนนนารายณ์,สุรินทร์,15.221463,103.871479,NaN,รถเพื่อการเกษตร
133552,9807445,2560,2017,37.0,NaN,NaN,NaN,NaN,NaN,NaN,...,2560-12-29 00:00:00,2560-12-29 00:00:00,1900-01-01 12:20:00,จานใหญ่,กันทรลักษ์,ศรีสะเกษ,14.747908,104.659693,NaN,รถเพื่อการเกษตร
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236680,1086651,2565,2022,37.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-02 00:00:00,NaN,NaT,NaN,NaN,ราชบุรี,13.539585,99.448334,NaN,รถเพื่อการเกษตร
238040,1073153,2565,2022,27.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-09 00:00:00,NaN,NaT,NaN,NaN,อุทัยธานี,15.410134,99.717749,Y349,รถเพื่อการเกษตร
238198,1069369,2565,2022,27.0,2.0,NaN,NaN,NaN,NaN,NaN,...,2565-04-11 00:00:00,NaN,NaT,NaN,NaN,พิษณุโลก,16.916779,100.812992,Y349,รถเพื่อการเกษตร
238238,1076549,2565,2022,65.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-05-08 00:00:00,NaN,NaT,NaN,NaN,สระแก้ว,13.816925,102.672986,X599,รถเพื่อการเกษตร
238328,1076835,2565,2022,48.0,1.0,NaN,NaN,NaN,NaN,NaN,...,2565-03-30 00:00:00,NaN,NaT,NaN,NaN,นครราชสีมา,15.006102,102.451974,Y349,รถเพื่อการเกษตร